# -*- coding: utf-8 -*-
"""[BAN 501] Module 6 Project Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsJOIQNuFTsQxkNgW7pmZlbe3zNlSJF4

**Module 6 Project Assignment - Bike Share Data Exploratory Analysis With Plotting**

Cole T. Catron

NAU - The W.A. Franke College of Business

Dr. Martin Hassell

October 13, 2024
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import data
data = pd.read_csv('/content/dc_bike_share.csv')

# Create a histogram showing the distribution of registered bike riders.
plt.hist(data['registered'], bins=30)
plt.xlabel('Number of Registered Bike Riders')
plt.ylabel('Frequency')
plt.title('Distribution of Registered Bike Riders')
plt.show()
print()

"""The distribution of the registered bike riders is right skewed, which demonstrates that the mean number of registered bike riders during any given hour, across both years, is much higher than the median, or middle 50% of all registered bike riders in the dataset. This tells me that there are many hours observed in the data that have less than 200 registered bike riders, indicating frequent time periods that have low demand, otherwise known as "slow hours."
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import data
data = pd.read_csv('/content/dc_bike_share.csv')

# Subset data for 2011 and 2012 separately
data_2011 = data[data['yr'] == 0]
data_2012 = data[data['yr'] == 1]

# Group median number of registered riders by month
median_2011 = data_2011.groupby('mnth')['registered'].median()
median_2012 = data_2012.groupby('mnth')['registered'].median()

# Gather all unique month observations
month = data['mnth'].unique()

# Create a bar plot showing the median number of registered bike riders grouped
# by month for 2011
plt.bar(month, median_2011)
plt.xlabel('Month')
plt.ylabel('Median Number of Registered Bike Riders')
plt.title('Median Number of Registered Bike Riders by Month (2011)')
plt.show()

# Create a bar plot showing the median number of registered bike riders grouped
# by month for 2012
plt.bar(month, median_2012)
plt.xlabel('Month')
plt.ylabel('Median Number of Registered Bike Riders')
plt.title('Median Number of Registered Bike Riders by Month (2012)')
plt.show()

"""In 2011, the highest demand from registered bike riders was in June while the lowest demand was in January. In 2012, demand differs from 2011 in that the highest demand from registered bike riders rather occurred in September despite having the same month for lowest demand.

When looking at both years, I noticed that demand increased in all months from 2011 to 2012. This indicates year-over-year business growth for the bike share company. September 2012 seems to have out grown June 2011, likely indicating that preferences may have changed from summer to fall for bike riding in the past year. No distinct behavioral changes have been made in January across both years other than increased demand across all months from 2011 to 2012.
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import data
data = pd.read_csv('/content/dc_bike_share.csv')

# Gather all unique hour observations
hour = data['hr'].unique()

# Subset data to only include July across 2011 and 2012
july = data[data['mnth'] == 7]

# Group by hour, showing median values
median_july = july.groupby('hr')['registered'].median()

# Create a bar plot showing the median number of registered bike riders by
# hour for the month of July across both years
plt.bar(hour, median_july)
plt.xlabel('Hour')
plt.ylabel('Median Number of Registered Bike Riders')
plt.title('Median Number of Registered Bike Riders by Hour (July)')
plt.show()

"""Across July 2011 and July 2012, the highest demand occurs at 5pm, followed then at 6pm. The third largest demand then occurs at 8 am. This tells me that bike share ridership for registered bikers occurs mostly in early mornings followed by early evenings in July. These demand cycles may be synonymous with typical morning and evening commutes for those who hold typical employment times during 9 am to 5 pm. This indicates that the bike share company is reliable for workers during the day.

The lowest demand from registered bike riders is earliest in the morning between 1 am and 5 am. Demand begins to pick up after 5 am, indicating that some people may be beginning to wake up and go on morning bike runs. Also, demand begins to fall significantly after 6 pm, where evening commuters have reached home, leaving only evening registered riders.
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import data
data = pd.read_csv('/content/dc_bike_share.csv')

# Gather all unique weekday observations
weekday = data['weekday'].unique()

# Group by weekday, showing median values
median_weekday = data.groupby('weekday')['registered'].median()

# Create a bar plot showing the median number of registered bike riders by
# weekday across all years
plt.bar(weekday, median_weekday)
plt.xlabel('Weekday')
plt.ylabel('Median Number of Registered Bike Riders')
plt.title('Median Number of Registered Bike Riders by Weekday')
plt.show()

"""Bike ridership for those registered generally rises from Sunday to Thursday with Thursday having the highest level of demand across all months and years. Friday and Saturday show significant decline in demand compared to the rest of the week with Saturday having the lowest demand out of days of the week.

The increase in registered bike demand could demonstrate the reliance on the bike share service that bikers have for commuting to and from work or school. The downward trajectory for Friday and Saturday could indicate lower demand on weekends as a result of other priorities or activities that can take precedent as people are less likely to commute to work or school at the end of the week.
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import data
data = pd.read_csv('/content/dc_bike_share.csv')

# Subset data for March 2011
march_2011_data = data[(data['mnth'] == 3) & (data['yr'] == 0)]

# Show scatterplot showing the relationship between 'windspeed' and
# 'registered'
# Add line of best fit to scatterplot
plt.scatter(march_2011_data['windspeed'], march_2011_data['registered'])
plt.xlabel('Windspeed')
plt.ylabel('Number of Registered Bike Riders')
plt.title('Relationship Between Windspeed and Number of Registered Bike Riders (March 2011)')
plt.show()

"""There is no distinguishable relationship that can be derived from the windspeed and number of registered bike riders in a given hour. As the data for March 2011 includes all weekday and daily observations, there could be a variety of particular behavioral patterns that can better explain the relationship than just the aggregated data for March 2011. Also, windspeed may not be characteristic of human decisions to ride bikes as some individuals may not be as sensitive to high speed winds compared to others.

---
Based upon my analysis, I would adjust the total number of bikes available based upon the level of demand during particular months, days of the week, and hours of the day. This will ensure that enough bikes are available to serve high volumes of registered riders during the work week in the summer and fall months of the year.

Another decision that could be enacted upon this analysis is to offer promtions during periods of low demand, such as weekends, where ridership drops compared to the work week. Lower-price fees for bike share rentals can target registered riders who may not always use bikes on weekends.
"""